### ISSUE TITLE
Cannot connect to IDR server to download data

### ISSUE THREAD

**Issue by njhanne** [WhoIsJack/katachi#1]
Hello, I seem to be having the same issue that was documented here:

https://forum.image.sc/t/idr-aspera-download-not-working-for-idr0085/44033

It appears to be an issue specific to your idr (idr0079) as I can connect to others using Aspera.

Thanks for making this amazing tool - I loved the paper and I'm looking forward to trying it out with some of my own images.

**Comment by WhoIsJack** [comment]
Hi @njhanne,

Thank you for bringing this to my attention!

I was able to confirm that there seems to be an issue with downloading idr0079 via Aspera (details below). Unfortunately, this is outside of my control, so someone from the IDR will need to look into it. Perhaps @francesw or @sbesson could have a look? That would be great!

----

Some details: I tried the following and got an authentication issue (manifested by a request for a password):

```
> ascp -TQ -m 140 -P 33001 -i "<path>\asperaweb_id_dsa.openssh" "idr0079@fasp.ebi.ac.uk:." "<path>\target_dir"

Password:

Password:
ascp.exe: failed to authenticate, exiting.

Session Stop  (Error: failed to authenticate)
```

The same command works for other idrs (I tested 0008, 0040, 0085):

```
> ascp -TQ -m 140 -P 33001 -i "<path>\asperaweb_id_dsa.openssh" "idr0008@fasp.ebi.ac.uk:." "<path>\target_dir"

<download runs...>
```

**Comment by sbesson** [comment]
@WhoIsJack @njhanne  thanks for the feedback and bringing this to our attention. It looks like the public Aspera access was never set up for this study, this is largely an oversight on our side.
I have contacted EBI IT to enable public access and we will update this issue as soon as something is ready to test on your side.

**Comment by sbesson** [comment]
Update: `idr0079` should now be downloadable via Aspera using the instructions describe in https://idr.openmicroscopy.org/about/download.html.

**Comment by WhoIsJack** [comment]
Can confirm that it works for me now. Thank you very much for addressing this so quickly, @sbesson!

I'm closing this issue. Please let me know if you're still having problems, @njhanne.

**Comment by njhanne** [comment]
It's working - thanks all!
